module Ruht
  class Attributes
    @boolean_attributes: untyped
    @content_attributes: untyped

    def initialize: (*untyped boolean_attributes, **untyped) -> void
    def to_s: -> String

    private
    def boolean_attributes: -> Array[Ruht::Attributes::BooleanAttribute]
    def content_attributes: -> Array[ContentAttribute | DataAttributes]
  end
end
