module Ruht
  class Element < Fragment
    @tag_name: Symbol
    @attributes: Ruht::Attributes | nil
    @children: Array[untyped]

    def initialize: (
      Symbol tag_name,
      Ruht::Attributes | nil attributes
    ) ?{ () -> untyped } -> void

    def to_s: -> String
  end
end
