module Ruht
  class Fragment
    extend Tags::ClassMethods
    include ClosureCapturing
    include Tags

    @children: Array[untyped]
    @evaluated: bool
    @child_block: (^(self) -> untyped | nil)
    @context: untyped

    def initialize: ?{ (self) -> untyped } -> void

    def render!: (untyped child_node) -> Array[untyped]
    def to_s: -> String

    private

    def eval_children!: -> void
    def can_render?: (untyped object) -> bool

    def method_missing: (Symbol method_name, *untyped args) -> untyped
    def respond_to_missing?: (Symbol method_name, *untyped args) -> bool
  end
end
