module Ruht
  module Tags
    TAG_NAMES: Array[Symbol]
    VOID_TAG_NAMES: Array[Symbol]

    def render!: (untyped _element) -> void
    def self.included: (Module receiver) -> void

    module ClassMethods
      def def_tag: (Symbol tag_name) -> void
      def def_void_tag: (Symbol tag_name) -> void
    end
  end
end
