module Ruht
  class VoidElement
    @tag_name: :input | :link | :meta
    @attributes: Ruht::Attributes

    def initialize: (:input | :link | :meta tag_name, Ruht::Attributes attributes) -> void
    def to_s: -> String
  end
end
