module Ruht
  class VoidElement
    @tag_name: Symbol | String
    @attributes: Ruht::Attributes

    def initialize: (Symbol | String tag_name, Ruht::Attributes attributes) -> void
    def to_s: -> String
  end
end
