# TypeProf 0.21.4

# Classes
module Ruht
  class Attributes
    class DataAttributes
      @values: Hash[String | Symbol, String | Symbol | bool | Numeric]

      def initialize: (
        void _name,
        Hash[String | Symbol, String | Symbol | bool | Numeric] values
      ) -> void
      def to_s: -> String
    end
  end
end
